# Generated by Django 3.2.9 on 2021-11-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cat_imgs/')),
                ('slug', models.SlugField(max_length=250)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '1. Categories',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('specs', models.TextField()),
                ('size', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
                ('image1', models.ImageField(upload_to='product_imgs/')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='product_imgs/')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='product_imgs/')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='product_imgs/')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='product_imgs/')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_not', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount', models.CharField(blank=True, max_length=150, null=True)),
                ('date_addeed', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'verbose_name_plural': '2. Product',
            },
        ),
    ]
