# Generated by Django 3.2.9 on 2021-11-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='banner_imgs')),
            ],
            options={
                'verbose_name_plural': '1. Banners',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering'], 'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '3. Product'},
        ),
    ]
