# Generated by Django 3.2.9 on 2021-11-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211115_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_not',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
