# Generated by Django 3.2.9 on 2021-11-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '2. Reviews'},
        ),
    ]
